run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: telemetry-api

  lll:
    line-length: 120

  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gosimple

issues:
  exclude-rules:
    # Allow long lines in test files
    - path: _test\.go
      text: "line is \\d+ characters"
      linters:
        - lll
