version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - export REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPONAME
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - docker build -t $REPO_URL:$IMAGE_TAG .

  post_build:
    commands:
      - docker push $REPO_URL:$IMAGE_TAG
      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPO_URL:$IMAGE_TAG > imageDetail.json
      - export IMAGE_URI=$REPO_URL:$IMAGE_TAG
      - envsubst < taskdef-template.json > taskdef.json
      - cat taskdef.json  # (opcional) debug para verificar se substituiu as variáveis

artifacts:
  files:
    - taskdef.json
    - appspec.yaml
    - imageDetail.json
