version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/telemetry?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
