version: "3.8"

services:
  app:
    build:
      context: .
    container_name: challenge-app-1
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_SSLMODE=${DB_SSLMODE}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: challenge-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
