services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    networks:
      - appnet

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - appnet

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1

    depends_on:
      - dynamodb-local
      - nats
    networks:
      - appnet

networks:
  appnet:
