services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - mynetwork

volumes:
  postgres_data:
    name: postgres_data

networks:
  mynetwork:
    driver: bridge
