# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgres-container
#     environment:
#       POSTGRES_USER: meuusuario
#       POSTGRES_PASSWORD: minhasenha
#       POSTGRES_DB: meubanco
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: go-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go

volumes:
  postgres-data:
