// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: devices.sql

package repository

import (
	"context"
)

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT device_id, registered_at FROM devices WHERE device_id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, deviceID)
	var i Device
	err := row.Scan(&i.DeviceID, &i.RegisteredAt)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (device_id) VALUES ($1) RETURNING device_id, registered_at
`

func (q *Queries) InsertDevice(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, insertDevice, deviceID)
	var i Device
	err := row.Scan(&i.DeviceID, &i.RegisteredAt)
	return i, err
}
