// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: gps_readings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertGPSReading = `-- name: InsertGPSReading :one
INSERT INTO
    gps_readings (device_id, latitude, longitude, collected_at)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, latitude, longitude, collected_at
`

type InsertGPSReadingParams struct {
	DeviceID    string           `json:"deviceId"`
	Latitude    pgtype.Numeric   `json:"latitude"`
	Longitude   pgtype.Numeric   `json:"longitude"`
	CollectedAt pgtype.Timestamp `json:"collectedAt"`
}

func (q *Queries) InsertGPSReading(ctx context.Context, arg InsertGPSReadingParams) (GpsReading, error) {
	row := q.db.QueryRow(ctx, insertGPSReading,
		arg.DeviceID,
		arg.Latitude,
		arg.Longitude,
		arg.CollectedAt,
	)
	var i GpsReading
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Latitude,
		&i.Longitude,
		&i.CollectedAt,
	)
	return i, err
}
