// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DeviceID     string
	Name         pgtype.Text
	Model        pgtype.Text
	RegisteredAt pgtype.Timestamp
}

type GpsReading struct {
	ID          pgtype.UUID
	DeviceID    string
	Latitude    pgtype.Numeric
	Longitude   pgtype.Numeric
	CollectedAt pgtype.Timestamp
}

type GyroscopeReading struct {
	ID          pgtype.UUID
	DeviceID    string
	X           float64
	Y           float64
	Z           float64
	CollectedAt pgtype.Timestamp
}

type Photo struct {
	ID          pgtype.UUID
	DeviceID    string
	ImageUrl    string
	CollectedAt pgtype.Timestamp
}
