// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DeviceID     string           `json:"deviceId"`
	RegisteredAt pgtype.Timestamp `json:"registeredAt"`
}

type GpsReading struct {
	ID          uuid.UUID        `json:"id"`
	DeviceID    string           `json:"deviceId"`
	Latitude    pgtype.Numeric   `json:"latitude"`
	Longitude   pgtype.Numeric   `json:"longitude"`
	CollectedAt pgtype.Timestamp `json:"collectedAt"`
}

type GyroscopeReading struct {
	ID          uuid.UUID        `json:"id"`
	DeviceID    string           `json:"deviceId"`
	X           float64          `json:"x"`
	Y           float64          `json:"y"`
	Z           float64          `json:"z"`
	CollectedAt pgtype.Timestamp `json:"collectedAt"`
}

type Photo struct {
	ID          uuid.UUID        `json:"id"`
	DeviceID    string           `json:"deviceId"`
	ImageUrl    string           `json:"imageUrl"`
	CollectedAt pgtype.Timestamp `json:"collectedAt"`
}
