// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
    domain "v3/internal/domain"
    mock "github.com/stretchr/testify/mock"
)

type MockCreatePhotoUseCase struct {
    mock.Mock
}

func (_m *MockCreatePhotoUseCase) Execute(input domain.PhotoDto, photoBytes []byte) (*domain.Photo, error) {
    ret := _m.Called(input, photoBytes)

    var r0 *domain.Photo
    var r1 error
    if rf, ok := ret.Get(0).(func(domain.PhotoDto, []byte) (*domain.Photo, error)); ok {
        r0, r1 = rf(input, photoBytes)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*domain.Photo)
        }
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}