// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
    domain "v3/internal/domain"
    mock "github.com/stretchr/testify/mock"
)

// MockCreateGPSUseCase is an autogenerated mock type for the CreateGPSUseCase type
type MockCreateGPSUseCase struct {
    mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *MockCreateGPSUseCase) Execute(input domain.GPSDto) (*domain.GPS, error) {
    ret := _m.Called(input)

    var r0 *domain.GPS
    var r1 error
    if rf, ok := ret.Get(0).(func(domain.GPSDto) (*domain.GPS, error)); ok {
        r0, r1 = rf(input)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*domain.GPS)
        }
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}