// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
    domain "v3/internal/domain"
    mock "github.com/stretchr/testify/mock"
)

// MockCreateGyroscopeUseCase is an autogenerated mock type for the CreateGyroscopeUseCase type
type MockCreateGyroscopeUseCase struct {
    mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *MockCreateGyroscopeUseCase) Execute(input domain.GyroscopeDto) (*domain.Gyroscope, error) {
    ret := _m.Called(input)

    var r0 *domain.Gyroscope
    var r1 error
    if rf, ok := ret.Get(0).(func(domain.GyroscopeDto) (*domain.Gyroscope, error)); ok {
        r0, r1 = rf(input)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*domain.Gyroscope)
        }
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}