CREATE TABLE gps (
	id SERIAL PRIMARY KEY,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL,
	mac TEXT NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL
);

CREATE TABLE gyroscope (
	id SERIAL PRIMARY KEY,
	x DOUBLE PRECISION NOT NULL,
	y DOUBLE PRECISION NOT NULL,
	z DOUBLE PRECISION NOT NULL,
	mac TEXT NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL
);

CREATE TABLE photo (
	id SERIAL PRIMARY KEY,
	filename TEXT NOT NULL,
	file_url TEXT NOT NULL,
	mac TEXT NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL
);
