// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: driver_gyroscope_data.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const saveGyroscope = `-- name: SaveGyroscope :exec
INSERT INTO driver_gyroscope_data (
    id,
    device_id,
    x,
    y,
    z,
    timestamp,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveGyroscopeParams struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  string             `json:"device_id"`
	X         float64            `json:"x"`
	Y         float64            `json:"y"`
	Z         float64            `json:"z"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Insert a new gyroscope reading
// Parameters: id, device_id, x, y, z, timestamp, created_at
func (q *Queries) SaveGyroscope(ctx context.Context, arg SaveGyroscopeParams) error {
	_, err := q.db.Exec(ctx, saveGyroscope,
		arg.ID,
		arg.DeviceID,
		arg.X,
		arg.Y,
		arg.Z,
		arg.Timestamp,
		arg.CreatedAt,
	)
	return err
}
