// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: driver_gps_data.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const saveGPS = `-- name: SaveGPS :exec
INSERT INTO driver_gps_data (
    id,
    device_id,
    latitude,
    longitude,
    timestamp,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveGPSParams struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  string             `json:"device_id"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Insert a new GPS record
// Parameters: id, device_id, latitude, longitude, timestamp, created_at
func (q *Queries) SaveGPS(ctx context.Context, arg SaveGPSParams) error {
	_, err := q.db.Exec(ctx, saveGPS,
		arg.ID,
		arg.DeviceID,
		arg.Latitude,
		arg.Longitude,
		arg.Timestamp,
		arg.CreatedAt,
	)
	return err
}
