// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: driver_photos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const savePhoto = `-- name: SavePhoto :exec
INSERT INTO driver_photos (
    id,
    device_id,
    file_path,
    recognized,
    timestamp,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SavePhotoParams struct {
	ID         uuid.UUID          `json:"id"`
	DeviceID   string             `json:"device_id"`
	FilePath   string             `json:"file_path"`
	Recognized bool               `json:"recognized"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Insert a new photo record
// Parameters: id, device_id, file_path, recognized, timestamp, created_at
func (q *Queries) SavePhoto(ctx context.Context, arg SavePhotoParams) error {
	_, err := q.db.Exec(ctx, savePhoto,
		arg.ID,
		arg.DeviceID,
		arg.FilePath,
		arg.Recognized,
		arg.Timestamp,
		arg.CreatedAt,
	)
	return err
}
