// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DriverGpsDatum struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  string             `json:"device_id"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DriverGyroscopeDatum struct {
	ID        uuid.UUID          `json:"id"`
	DeviceID  string             `json:"device_id"`
	X         float64            `json:"x"`
	Y         float64            `json:"y"`
	Z         float64            `json:"z"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DriverPhoto struct {
	ID         uuid.UUID          `json:"id"`
	DeviceID   string             `json:"device_id"`
	FilePath   string             `json:"file_path"`
	Recognized bool               `json:"recognized"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
