// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	// Insert a new GPS record
	// Parameters: id, device_id, latitude, longitude, timestamp, created_at
	SaveGPS(ctx context.Context, arg SaveGPSParams) error
	// Insert a new gyroscope reading
	// Parameters: id, device_id, x, y, z, timestamp, created_at
	SaveGyroscope(ctx context.Context, arg SaveGyroscopeParams) error
	// Insert a new photo record
	// Parameters: id, device_id, file_path, recognized, timestamp, created_at
	SavePhoto(ctx context.Context, arg SavePhotoParams) error
}

var _ Querier = (*Queries)(nil)
