// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
    mock "github.com/stretchr/testify/mock"
)

// MockAWSService is an autogenerated mock type for the AWSService type
type MockAWSService struct {
    mock.Mock
}

// UploadPhoto provides a mock function with given fields: deviceID, photoBytes, timestamp
func (_m *MockAWSService) UploadPhoto(deviceID string, photoBytes []byte, timestamp int64) (string, error) {
    ret := _m.Called(deviceID, photoBytes, timestamp)

    var r0 string
    var r1 error
    if rf, ok := ret.Get(0).(func(string, []byte, int64) (string, error)); ok {
        r0, r1 = rf(deviceID, photoBytes, timestamp)
    } else {
        r0 = ret.String(0)
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}

// ComparePhoto provides a mock function with given fields: deviceID, filePath
func (_m *MockAWSService) ComparePhoto(deviceID string, filePath string) (bool, error) {
    ret := _m.Called(deviceID, filePath)

    var r0 bool
    var r1 error
    if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
        r0, r1 = rf(deviceID, filePath)
    } else {
        r0 = ret.Bool(0)
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}