// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
    domain "v3/internal/domain"
    mock "github.com/stretchr/testify/mock"
)

// MockPhotoRepository is an autogenerated mock type for the PhotoRepository type
type MockPhotoRepository struct {
    mock.Mock
}

// Create provides a mock function with given fields: photo
func (_m *MockPhotoRepository) Create(photo *domain.Photo) (*domain.Photo, error) {
    ret := _m.Called(photo)

    var r0 *domain.Photo
    var r1 error
    if rf, ok := ret.Get(0).(func(*domain.Photo) (*domain.Photo, error)); ok {
        r0, r1 = rf(photo)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*domain.Photo)
        }
        if ret.Get(1) != nil {
            r1 = ret.Get(1).(error)
        }
    }

    return r0, r1
}