# Generated by Django 5.2.3 on 2025-06-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_gpsdata_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='telemetry/photos', verbose_name='telemetry'),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telemetry.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gyroscope',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telemetry.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telemetry.device'),
            preserve_default=False,
        ),
    ]
