# Generated by Django 5.2.3 on 2025-07-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_device_alter_photo_photo_gpsdata_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.JSONField(null=True),
        ),
    ]
