# Generated by Django 5.2.3 on 2025-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='hash',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
