# Generated by Django 5.2.3 on 2025-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_alter_photo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='face_contains',
            field=models.BooleanField(default=False),
        ),
    ]
