# Generated by Django 5.2.3 on 2025-07-01 16:40

import telemetry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_photo_face_contains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=telemetry.fields.EncryptedTextField(max_length=32),
        ),
    ]
