// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/telemetry/gps": {
            "post": {
                "description": "valida e persiste dados de gps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "envia dados de gps",
                "parameters": [
                    {
                        "description": "dados do gps",
                        "name": "gps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GpsData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "erro de validação",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "método não permitido",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/telemetry/gyroscope": {
            "post": {
                "description": "valida e persiste dados de giroscópio",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "envia dados de giroscópio",
                "parameters": [
                    {
                        "description": "dados do giroscópio",
                        "name": "gps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GyroData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "erro de validação",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "método não permitido",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/telemetry/photo": {
            "post": {
                "description": "valida e persiste fotos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "envia fotos",
                "parameters": [
                    {
                        "description": "foto",
                        "name": "gps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.PhotoData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "erro de validação",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "método não permitido",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.GpsData": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        },
        "main.GyroData": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "z": {
                    "type": "number"
                }
            }
        },
        "main.PhotoData": {
            "type": "object",
            "properties": {
                "photo": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "api de telemetria",
	Description:      "recebe dados de sensores e publica via nats",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
