ALTER TABLE gyroscope ADD COLUMN mac_address VARCHAR(255) NOT NULL;
ALTER TABLE geolocation ADD COLUMN mac_address VARCHAR(255) NOT NULL;
ALTER TABLE photo ADD COLUMN mac_address VARCHAR(255) NOT NULL;