name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Instalar dependências
        run: go mod tidy

      - name: Build do app
        run: go build -tags netgo -ldflags '-s -w' -o app ./cmd/api

      - name: Rodar testes
        run: go test ./... -v

      - name: Instalar Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH

      - name: Deploy no Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy service https://challenge-8sus.onrender.com --wait
