name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    # services:
    #   nats:
    #     image: nats:latest
    #     ports:
    #       - 4222:4222

    env:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: us-east-1
      NATS_URL: nats://localhost:4222

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Instalar dependências
        run: go mod tidy

      - name: Build do app
        run: go build -tags netgo -ldflags '-s -w' -o app ./cmd/api

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Subir serviços com docker-compose
        run: docker-compose up -d

      - name: Rodar testes
        run: go test ./... -v -cover

      - name: Instalar Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH

      - name: Deploy no Render
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy service https://challenge-8sus.onrender.com --wait
